### ISSUE TITLE
TOKEN LOGGER (https://streamable.com/8aookn)

### ISSUE THREAD

**Issue by NotUnknown6** [9tro/unlockervip-source#4]
DO NOT OPEN IT, PUT THE TOOL INTO DnSpy, He Is Stealing EVERYTHING. DO NOT OPEN

**Comment by boogieiskool** [comment]
lol

**Comment by NotUnknown6** [comment]
> lol

How is that funny? put the EXE into DnSpy and see for yourself

**Comment by 9tro** [comment]
lmao. this dude got no life

**Comment by Reignisurdaddy** [comment]
yo i opened this it disabled my access to task manager my wifi and it started coming up with errors saying Discord AIO

**Comment by NotUnknown6** [comment]
> 

Discord AIO is a Token Logger for discord. Lookup Discord AIO on github.

**Comment by 9tro** [comment]
lol what are you talking about. only a skid would know what that is

**Comment by 9tro** [comment]
the full source is posted you fucking retard. how bout you read

**Comment by NotUnknown6** [comment]
bruh ur retarded. LMAOOOOO. that exe u had in the GitHub was a RedLine Stealer, it legit stole evrything from ur computer thats why i made a thread to tell everyone that ur a Token Logger, + i only know what DiscordAIO is, is bc i looked it up on GitHub after that dude said it

**Comment by 9tro** [comment]
lmao. dont got time for skids. 💀 not my problem that you came on github looking for free warzone unlock tools. if you werent a rard you'd know you can build the full source and it'll work. btw redline stealer costs 100 dollars a month so idk what niggas you fw that have redline, but props to them for paying that much 🤡

**Comment by NotUnknown6** [comment]
i make my own cod cheats lmao. i know what im doing i just wanted to check out a GitHub cheat a buddy of mine sent me to make sure the cheat was safe. Then i looked at it and it was a cheap ass (DiscordAIO) redline stealer off of github. stay mad pussy get exposed.

**Comment by boogieiskool** [comment]
> i make my own cod cheats lmao. i know what im doing i just wanted to check out a GitHub cheat a buddy of mine sent me to make sure the cheat was safe. Then i looked at it and it was a cheap ass (DiscordAIO) redline stealer off of github. stay mad pussy get exposed.
> 
> 

Where did you learn to do that? Im learning c++ but where did you learn that stuff?

**Comment by 9tro** [comment]
> i make my own cod cheats lmao. i know what im doing i just wanted to check out a GitHub cheat a buddy of mine sent me to make sure the cheat was safe. Then i looked at it and it was a cheap ass (DiscordAIO) redline stealer off of github. stay mad pussy get exposed.

lmao who's mad 💀 dont try and make it seem like i'm mad so you can feel big and bad on the internet broski. jus cus you looked up password stealers on google and found redline doesn't mean yk what you talkin bout lmao. dk who you exposing cus like i said. full source is right there if you wanna build it lmao

**Comment by 9tro** [comment]
this is also coming from the skid that put it in dnspy 💀

**Comment by 9tro** [comment]
pretty crazy huh

**Comment by RabbitNation** [comment]
It is a rat though 😂

**Comment by DontSpectate** [comment]
How do I remove this rat? I didn’t see issues before downloading and saw it accessing my files. I blocked it and wiped my pc. Is that All I need to do?

**Comment by RabbitNation** [comment]
It should be. Reset your discord password just in case.

**Comment by DontSpectate** [comment]
Okay I wiped my pc again just for safe measures lol.

**Comment by RabbitNation** [comment]
Slide me yo discord to talk about it

**Comment by DontSpectate** [comment]
DontSpectate#8741

**Comment by NotUnknown6** [comment]
https://streamable.com/8aookn
Watch That @9tro 
U Look Hella Stupid Rn. LMAOOO

**Comment by DAFFYDUCK007** [comment]
> Slide me yo discord to talk about it

can u help me my dicord is Jati#5029 pleas help and whats urs i have a 100+ friend request

**Comment by Kokirix** [comment]
Kokiri#8556

**Comment by stressatoo** [comment]
> Slide me yo discord to talk about it

yo Stress#9999 add me

**Comment by Zzexer** [comment]
> 

I just gotta delete the file for it and change my pw for discord and I'm good right 😅

**Comment by msfnxy** [comment]
ay thank you bruh i almost opened it, got dnspy myself just to check if the vid was fake and nah its all right there bro couldn't even atleast try to hide it lol
