### ISSUE TITLE
unlockervip 

### ISSUE THREAD

**Issue by Dani281938** [9tro/unlockervip-source#6]
can you put the tool not the src :)

**Comment by 9tro** [comment]
> can you put the tool not the src :)

there, i've added it

**Comment by Dani281938** [comment]
couldn't you just put it back together with the src XD?

**Comment by Dani281938** [comment]
THANKS

**Comment by Dani281938** [comment]
every time i open it i quit discord, is it a virus or something?

**Comment by Dani281938** [comment]
why?
